"""added auth

Revision ID: 414020a8813e
Revises: 82bb871ec08e
Create Date: 2022-09-01 15:48:54.782928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '414020a8813e'
down_revision = '82bb871ec08e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
